'''
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

def gen_tri_num(pos):
    ''' find triangle number at position pos '''
    number = 0
    for i in xrange(1, pos + 1):
        number += i
    return number

def divisor_count(number):
    '''returns the number of divisors of number'''
    count = 0
    for i in xrange(1, number+1):
        if number % i == 0:
            count += 1
    return count
    
for i in xrange(1, 100000):
    tri_number = gen_tri_num(i)
    if divisor_count(tri_number) > 500:
        print tri_number
        break
    
        